language: node_js
node_js:
  - "stable"
  - "4"
  - "6"
  - "8"

env:
  global:
    - BUILD_TIMEOUT=10000

script:
  - node_modules/.bin/acorn --ecma5 dist/buble-browser.cjs.js
  - node_modules/.bin/acorn --ecma5 dist/buble-browser-deps.umd.js
